services:
  - type: web
    name: JobSyncAPI
    env: node
    # Temporarily add 'ls -la /usr/bin' to find the browser executable
    buildCommand: "npm install && ls -la /usr/bin"
    startCommand: "node index.js"
    systemDependencies:
      - name: chromium-browser 
        type: apt